//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasinoWPF.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bets
    {
        public int BetID { get; set; }
        public int SessionID { get; set; }
        public int UserID { get; set; }
        public decimal Amount { get; set; }
        public string BetValue { get; set; }
        public string Result { get; set; }
        public Nullable<decimal> WinAmount { get; set; }
        public Nullable<System.DateTime> BetTime { get; set; }
    
        public virtual GameSessions GameSessions { get; set; }
        public virtual Users Users { get; set; }
    }
}
